yolo_model:

  config_file:
    name: yolov3-flir.cfg
  weight_file:
    name: yolov3-flir_best.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - bicycle
      - car
      - dog
